const styles: Record<string, React.CSSProperties> = {
    page: {
        minHeight: "100vh",
        background: "linear-gradient(135deg, #0f0f1a 0%, #1a1a2e 50%, #16213e 100%)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontFamily: "'DM Sans', system-ui, sans-serif",
        padding: "1.5rem",
    },
    card: {
        background: "#ffffff",
        borderRadius: "20px",
        padding: "2.5rem",
        width: "100%",
        maxWidth: "420px",
        boxSizing: "border-box",
    },
    brand: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        marginBottom: "2rem",
    },
    logoMark: { lineHeight: 0 },
    brandName: {
        fontSize: "20px",
        fontWeight: 700,
        color: "#1a1a2e",
        letterSpacing: "-0.5px",
    },
    tabs: {
        display: "flex",
        background: "#f4f4f6",
        borderRadius: "10px",
        padding: "4px",
        marginBottom: "1.75rem",
    },
    tab: {
        flex: 1,
        padding: "8px",
        border: "none",
        borderRadius: "7px",
        background: "transparent",
        fontSize: "14px",
        fontWeight: 500,
        color: "#888",
        cursor: "pointer",
        transition: "all 0.2s",
    },
    tabActive: {
        background: "#1a1a2e",
        color: "#e8c547",
        boxShadow: "0 1px 3px rgba(0,0,0,0.15)",
    },
    heading: { marginBottom: "1.5rem" },
    title: {
        fontSize: "22px",
        fontWeight: 700,
        color: "#1a1a2e",
        margin: "0 0 4px",
        letterSpacing: "-0.5px",
    },
    subtitle: {
        fontSize: "14px",
        color: "#888",
        margin: 0,
    },
    alertError: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        background: "#fff0f0",
        border: "1px solid #ffd0d0",
        borderRadius: "8px",
        padding: "10px 12px",
        fontSize: "13px",
        color: "#c0392b",
        marginBottom: "1rem",
    },
    alertSuccess: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        background: "#f0fff4",
        border: "1px solid #c3e6cb",
        borderRadius: "8px",
        padding: "10px 12px",
        fontSize: "13px",
        color: "#1e7e34",
        marginBottom: "1rem",
    },
    alertIcon: {
        fontWeight: 700,
        flexShrink: 0,
    },
    fields: {
        display: "flex",
        flexDirection: "column",
        gap: "1rem",
        marginBottom: "1.5rem",
    },
    fieldGroup: {
        display: "flex",
        flexDirection: "column",
        gap: "6px",
    },
    flexRow: {
        display: "flex",
        gap: "1rem",
    },
    label: {
        fontSize: "13px",
        fontWeight: 500,
        color: "#444",
    },
    input: {
        padding: "10px 14px",
        borderRadius: "8px",
        border: "1.5px solid #e8e8ec",
        fontSize: "14px",
        color: "#1a1a2e",
        outline: "none",
        transition: "border-color 0.2s",
        background: "#fafafc",
        fontFamily: "inherit",
    },
    submitBtn: {
        width: "100%",
        padding: "12px",
        background: "#1a1a2e",
        color: "#e8c547",
        border: "none",
        borderRadius: "10px",
        fontSize: "15px",
        fontWeight: 600,
        cursor: "pointer",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "8px",
        letterSpacing: "0.2px",
        fontFamily: "inherit",
    },
    submitBtnDisabled: {
        opacity: 0.7,
        cursor: "not-allowed",
    },
    spinner: {
        width: "16px",
        height: "16px",
        border: "2px solid rgba(232,197,71,0.3)",
        borderTopColor: "#e8c547",
        borderRadius: "50%",
        animation: "spin 0.7s linear infinite",
        display: "inline-block",
    },
    footer: {
        textAlign: "center",
        fontSize: "13px",
        color: "#888",
        marginTop: "1.25rem",
        marginBottom: 0,
    },
    linkBtn: {
        background: "none",
        border: "none",
        color: "#1a1a2e",
        fontWeight: 600,
        cursor: "pointer",
        fontSize: "13px",
        padding: 0,
        fontFamily: "inherit",
        textDecoration: "underline",
        textUnderlineOffset: "2px",
    },
};

export default styles;